services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - database_volume:/data
    environment:
      - FLASK_APP=src:create_app()
      - FLASK_DEBUG=1
      - SECRET_KEY=tu_clave_secreta_2025

volumes:
  database_volume: